### PR TITLE
Create Operator Sales Detail page

### PR DESCRIPTION
**Pull request by ayeshatasaduq**
Kindly create page for Operator Sales Detail as per wire frames

https://app.diagrams.net/#Wb!HT-wfrbGcEqM5DoBIQXmPY19VMxuO41MpyWO-AFCZ9OE0Sc7-s_LQpcniXtoUBo4%2F01ZZKZDJSFHBFVK66RZVHIRLBZ73QZA453

### CODE REVIEW

**Comment by ayeshatasaduq** [comment]
image

**Review by OmerAli277 — CHANGES_REQUESTED** [review]
Read about the nested Vuejs router, and check how it is used in the analytics page.
Apply the same in your case.

**Review by OmerAli277 — CHANGES_REQUESTED** [review]
Intend your code. Focus on code practices and styling. 
If you only focus on functionality it would be much difficult for other programmers to understand your code.

**Review by OmerAli277 — DISMISSED** [review]

**Comment by ayeshatasaduq** [comment]
image

**Review by OmerAli277 — APPROVED** [review]

**Pull request merged**
